version: '3'

services:
  payload:
    image: test-posts-lexical
    ports:
      - '3001:3001'
    volumes:
      - media:/app/media
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - payload-network

  # Ensure your DATABASE_URL uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - payload-network

networks:
  payload-network:
    driver: bridge

volumes:
  data:
  media:
